[package]
name = "learncontrolwasm"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.13.0"
ndarray-stats = "0.3.0"
wasm-bindgen = "0.2"
rustnomial = "0.1.0"
num = ""
